<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Vittal.DAL\Vittal.DAL.csproj" />
    <ProjectReference Include="..\Vittal.DTO\Vittal.DTO.csproj" />
    <ProjectReference Include="..\Vittal.Entity\Vittal.Entity.csproj" />
    <ProjectReference Include="..\Vittal.Utility\Vittal.Utility.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
